### ISSUE TITLE
Proposta redesign UI

### ISSUE THREAD

**Issue by Nicuz** [Fast0n/iliad#2]
Innanzitutto vi faccio i miei complimenti per l'app, completissima! Il progetto mi piace e ho pensato di contribuire con una proposta di redesign che segue gli ultimi trend di Google introdotti nelle nuove app Google Tasks, Files Go, Datally e la versione desktop di Gmail. Non ci sono ancora delle linee guida ufficiali ma è evidente che sarà questa la direzione che prenderà il Material Design con l'arrivo di Android P.

Ho realizzato due mockup, il primo riprende il design attuale e lo riadatta, il secondo invece è molto più minimale e ispirato a Google Tasks e Gmail. Al momento si tratta solo della schermata principale.
<img width="751" src="https://user-images.githubusercontent.com/3705140/41467020-19a62318-70a5-11e8-8d47-7c6e62710345.png">

Spero vi piacciano, nel caso dovesse servire posso allegare il file di Sketch 😄

**Comment by Fast0n** [comment]
Ciao Domenico ho parlato con il mio collega Matteo e se tu vorresti
contribuire va benissimo per noi, purtroppo noi non possiamo retribuire
nessuno, al momento è bene che tu lo sappia. Se per te va bene ti do il mio
contatto telegram @fast0n per contattarmi e iniziare a lavorarci, in caso
rifiuterai ti ringraziamo comunque 😄.

Con la speranza che ci contatterai, ti saluto Massimiliano Montaleone

Il giorno ven 15 giu 2018 alle ore 14:25 Domenico Majorana <
notifications@github.com> ha scritto:
