### ISSUE TITLE
Sovreapposizione elementi su telefoni con schermi di piccole dimensioni

### ISSUE THREAD

**Issue by ElCresh** [Fast0n/iliad#3]
Salve,
ho notato che su schermi di piccole dimensini la lista prensete nel dettaglio dell'offerta corrente non permette il corretto scorrimento impedendo la visione dello stato degli MMS (che vengono coperti dai pulsanti).
E' facilmente riproducibile da AVD creando un dispositivo con le caratteristiche del Galaxy Nexus.

![immagine](https://user-images.githubusercontent.com/9625583/41493098-1f3976fe-7104-11e8-91c0-842979e4c10e.png)

**Comment by Fast0n** [comment]
Ciao grazie per la segnalazione stiamo lavorando per cambiare il design dell'app, per farlo ci vorrà del tempo 😄

**Comment by Fast0n** [comment]
Ho risolto parzialmente il problema, nel pomeriggio carico il tutto.

Ps. Dimmi se funziona o meno quando sarà

**Comment by ElCresh** [comment]
Ok perfetto. Appena arriva l'aggiornamento inizio le prove.

**Comment by ElCresh** [comment]
![immagine](https://user-images.githubusercontent.com/9625583/41609368-ec0b105a-73ea-11e8-8402-5ba207cfe516.png)

Ho provato l'ultima versione del codice e ora sembra impaginare correttamente lo scorrimento anche su schermi di piccole dimensioni.

**Comment by Fast0n** [comment]
Corretto con l'ultima versione 😄 

<img width="500" alt="screen shot 2018-06-21 at 18 03 10" src="https://user-images.githubusercontent.com/5260133/41782497-b62f95c6-763a-11e8-8957-6b982d84e966.png">
