### ISSUE TITLE
Divisone richieste su API Node.JS

### ISSUE THREAD

**Issue by ElCresh** [Fast0n/iliad#7]
Questo più che un problema è un idea di miglioramento.
Osservando il codice per le API ho notato che tutte le richieste arrivano su '/' e poi, tramite i parametri si individua quale richiesta effettivamente eseguire. Pensavo se si poteva rendere più specifica la richiesta in partenza ad esempio utilizzando '/segreteria/' per le richieste riguardanti la segreteria telefonica o '/info' per le info dell'utente. Che ne pensate?

**Comment by ElCresh** [comment]
Se una mano vi può tronare utile me ne posso occupare io.

**Comment by MattVoid** [comment]
Ciao, mi occupo io delle API, in questo momento sono ancora in fase di sviluppo, una volta ultimate, provvederemo a sistemare meglio il codice, dato che per adesso stiamo dando priorità al funzionamento, grazie per il suggerimento
